# Generated by Django 3.0.2 on 2020-01-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colcon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rno',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='channels',
            field=models.ManyToManyField(null=True, to='colcon.Channel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='joindate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('S', 'Student'), ('F', 'Faculty')], default='S', max_length=10),
        ),
    ]
